### ISSUE TITLE
Repetición de una dinamicidad a lo largo de un desplazamiento

### ISSUE THREAD

**Issue by jmlahoz** [agarsev/signotator#9]
Habíamos llegado a la conclusión de que signos como PEZ o AMIGOS se pueden signotar con una doble evolución (77) o un doble giro ($$) y luego un único gran desplazamiento (->) que hace de portador. ¿Qué pasa, sin embargo, cuando la dinamicidad que se itera en el desplazamiento es también un desplazamiento?

Hay casos de movimientos circulares (TRADICIÓN, TODOS LOS DÍAS) . La lógica pediría transcribir I:Bx:[]H:(H,F)(H,F):->:F. Se plantean dos problemas:

- (H,F)(H,F) ya satura el campo de desplazamiento, pero luego queremos meter otro para ->
- (H,F)(H,F) está en antifase (~), pero el rectilíneo está en acompañamiento (&). ¿Podríamos indicar la antifase justo después de los movimientos circulares y el acompañamiento al final del signo?

En otros casos, el movimiento que se repite dentro del portador también es rectilíneo (NEPAL, A RAYAS). De nuevo, para NEPAL habría que transcribir algo así como pir:Xh:->->:HL:->:Y. Pueden parecer dos sílabas, al indicar un nuevo desplazamiento después del primero. También puede parecer contradictoria una dirección del movimiento que sea HL (solo se entiende si se interpreta en un contexto del portador Y). En el caso de A RAYAS, solo sería ->->:L:->:Y

La alternativa (especificar movimientos diagonales a HY, XY, HY, XY, como si fueran muchas sílabas) no me gusta cognitivamente (se pierde la intuición del portador) y tampoco permitiría poner una R (porque no repites la misma sílaba sino una secuencia de dos sílabas).

¿Qué opinas?

**Comment by jmlahoz** [comment]
Estoy pensando que el movimiento portador abre un "contenedor" para otra información de dinamicidad (que puede ser E, G o D). Es un poco similar al lugar H2 que abre un contenedor para otra información de Q, O, (L). Entonces, en lugar de corchetes como en H2, podríamos usar llaves, que están sin usar. Creo que esto da respuesta a todos los ejemplos que teníamos. Se asume que el contenido entre llaves se repite al menos durante dos iteraciones.

Movimiento portador con evolución
PEZ: IC-:Bx:{7}->X
Movimiento portador con giro
AMIGOS: pi+O:Xf:[]*:{$}->X
Movimiento portador con desplazamiento
- Con desplazamiento circular = rizo (conclusión: el 3 es emergente; ya no hace falta)
TRADICIÓN: I:Bx:HomY:{(H,F)~}->F:&
TIRABUZÓN: I:Bh:CabY:{(F,X)}->L
- Con desplazamiento rectilíneo
A RAYAS VERTICALES: pir:Fy:{->L}->Y
A RAYAS HORIZONTALES: pir:Fh:{->Y}->L
- Con desplazamiento en zigzag. Creo que el 2 sí sigue haciendo falta para diferenciar la cualidad de las repeticiones rectilíneas, aunque también se puede crear como emergente: es como si en los ejemplos anteriores hubiera una R dentro de las llaves, y en el zigzag hubiera una N.
NEPAL: pir:Fy:{2}->Y

¿Qué te parece?

**Comment by agarsev** [comment]
Me parece **muy buena idea**!

lo "malo" es que supone un cambio muy profundo tanto a nivel de ortografía como a nivel de modelo, así que tenemos que darle una buena vuelta para formalizarlo bien.

Sobre todo veo que hay que pensar bien las fases y repeticiones, porque todo esto está muy ligado al movimiento y la sincronización temporal.

En cuanto a NEPAL, no me gusta mucho el 2, quizá probablemente tampoco en general en sí. En este modelo, creo que el zigzag es más claro representarlo como dices como `{->'A:N}->'B` (además captura bien los paralelos y frecuente neutralización fonética con `{->'A:R}->'B`). Como dices el R se puede omitir porque se da por supuesto (si no hubiera R, no habría dos niveles de movimiento)

とにかく Me parece muy buena idea, tenemos que un día verlo en profundidad. Requiere revisar el modelo bastante, no sé si eres consciente hasta qué punto, pero nos da una buena oportunidad para mejorarlo.

**Comment by jmlahoz** [comment]
Genial, pues quedamos un día y lo vemos. Y es verdad que lo lógico es poner el 2 también como emergente y ahorrar la R (en oposición a N) como marca de repetición por defecto en el interior de las llaves.

Entonces, ¿empiezo a transcribir así las palabras que me vaya encontrando? ¿O creo una bandera nueva para los movimientos portadores y lo dejamos pendiente? En cualquier caso, además, puedo buscar automáticamente todos los casos de 2, 3, o cosas como 77, $$, que ya habíamos puesto en palabras anteriores, y cambiarlas directamente o añadirles la misma bandera para revisar la transcripción más tarde cuando lo tengamos claro.

**Comment by agarsev** [comment]
Ponles bandera en cualquier caso, yo creo, por agilizar posibles búsquedas futuras, y ve transcribiendo con llaves, yo creo, sí. Lo único que el signotador no te va a poder ayudar con eso,  así que tendrás que hacerlo a mano 😅

**Comment by agarsev** [comment]
En cuanto a los existentes, yo que tú no perdería el tiempo en ello, lo revisaremos cuando tengamos claro cómo ponerlo

**Comment by agarsev** [comment]
Se implementará en #15
